### ISSUE TITLE
"Failed to open Bazel as a zip file" while building tensorboard

### ISSUE THREAD

**Issue by d-wang03** [hongxu-jia/meta-tensorflow#1]
Here is the log:
DEBUG: Executing shell function do_compile
file is invalid or corrupted (missing end of central directory record)
Cannot find central directory
FATAL: Failed to open Bazel as a zip file: (error: 5): Input/output error
WARNING: exit code 36 from a shell command.
ERROR: Function failed: do_compile (log file is located at /home/supervisor/osbuilder/bstos/build/tmp-glibc/work/core2-64-bst-linux/tensorboard/1.12.2-r0/temp/log.do_compile.1961)

How to resolve it ? Please help!

**Comment by hongxu-jia** [comment]
Seems a parallel build issue, could you buuild tensorboard again
such as `bitbake tensorboard -ccleansstate && bitbake tensorboard'

**Comment by hongxu-jia** [comment]
The errors occurs while multiple recipe (tensorflow-native, tensorboard) invoke one bazel.

**Comment by d-wang03** [comment]
`bitbake tensorboard -ccleansstate && bitbake tensorboard'  does not resolve the problem.
I manually run bazel under sysroot in tensorboard build dir, and get the same error info.
I checked bazel binary under bazel-native, only the binary under output is correct. It seems the broken bazel comes from "    create_cmdline_wrapper ${D}/${bindir}/bazel \$BAZEL_ARGS" in do_install () in bazel-native.bb

**Comment by d-wang03** [comment]
In the install log of bazel-native, the $BAZEL_ARGS is not expanded. Is this the reason?

+ create_cmdline_wrapper /home/supervisor/osbuilder/bstos/build/tmp-glibc/work/x86_64-linux/bazel-native/0.23.2-r0/image//home/supervisor/osbuilder/bstos/build/tmp-glibc/work/x86_64-linux/bazel-native/0.23.2-r0/recipe-sysroot-native/usr/bin/bazel $BAZEL_ARGS

**Comment by hongxu-jia** [comment]
I may the following issue,
https://github.com/bazelbuild/bazel/issues/2978
please manually try `zip -A bazel' to prove it

**Comment by d-wang03** [comment]
there are bazel and bazel.real under recipe-sysroot-native/usr/bin. 
bazel.real is a zip file. while tring to zip bazel, I get the following error info:
build/tmp-glibc/work/core2-64-bst-linux/tensorboard/1.12.2-r0/recipe-sysroot-native/usr/bin$ zip -A bazel
        zip warning: missing end signature--probably not a zip file (did you
        zip warning: remember to use binary mode when you transferred it?)
        zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (bazel)

**Comment by hongxu-jia** [comment]
build/tmp-glibc/work/core2-64-bst-linux/tensorboard/1.12.2-r0/recipe-sysroot-native/usr/bin$ zip -A bazel.real

**Comment by d-wang03** [comment]
$ zip -A bazel.real
Zip entry offsets do not need adjusting

and I still get  FATAL: Failed to open Bazel as a zip file: (error: 5): Input/output error

**Comment by hongxu-jia** [comment]
Could you `git pull' and build again, here is the commit
https://github.com/hongxu-jia/meta-tensorflow/commit/25af4daadaafeb67f167791303e9fe8fb9f34903

**Comment by d-wang03** [comment]
Thanks! I spent a really long time to remove the whole build dir, then try your commit. 
The bazel is OK now. However, the do_compile() for `bitbake tensorboard` still failed with the following infomation:

ERROR: tensorboard-1.12.2-r0 do_compile: Function failed: do_compile (log file is located at /home/user/build/tmp-glibc/work/core2-64-oe-linux/tensorboard/1.12.2-r0/temp/log.do_compile.1239)
ERROR: Logfile of failure stored in: /home/supervisor/diwang/build/tmp-glibc/work/core2-64-oe-linux/tensorboard/1.12.2-r0/temp/log.do_compile.1239
Log data follows:
| DEBUG: Executing shell function do_compile
| Extracting Bazel installation...
| Starting local Bazel server and connecting to it...
| INFO: Invocation ID: 458e6c42-7c36-4865-a3d7-5e29496534b0
| Loading:
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| Loading: 0 packages loaded
| ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted
| ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted
| INFO: Elapsed time: 200.386s
| INFO: 0 processes.
| FAILED: Build did NOT complete successfully (0 packages loaded)
| ERROR: Build failed. Not running target
| FAILED: Build did NOT complete successfully (0 packages loaded)
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/user/build/tmp-glibc/work/core2-64-oe-linux/tensorboard/1.12.2-r0/temp/log.do_compile.1239)
ERROR: Task (/home/user/meta-tensorflow/recipes-framework/tensorflow/tensorboard_1.12.2.bb:do_compile) failed with exit code '1'

**Comment by hongxu-jia** [comment]
In tensorboard WORKSPACE, it seems download @org_tensorflow//tensorflow failed,
would you please rebuild tensorboard (bitbake tensorboard -ccleansstate && bitbake  tensorboard)
...
http_archive(
    name = "org_tensorflow",
    sha256 = "a0d7eea4c4e4b526cdba624f706bfbcc87a7923bb09904dfab22589a6bd142f2",
    strip_prefix = "tensorflow-6ef428bd6e83b0930266bf922eaa2f4a60e8328a",
    urls = [ 
        "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/6ef428bd6e83b0930266bf922eaa2f4a60e8328a.tar.gz",  # 2018-12-06
        "https://github.com/tensorflow/tensorflow/archive/6ef428bd6e83b0930266bf922eaa2f4a60e8328a.tar.gz",
    ],  
)
...
load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
...

**Comment by hongxu-jia** [comment]
Does the following file  exist?
/home/user/build/tmp-glibc/work/core2-64-oe-linux/tensorboard/1.12.2-r0/bazel/output_base/external/org_tensorflow/tensorflow/workspace.bzl

**Comment by d-wang03** [comment]
It seems the download failed. under /home/user/build/tmp-glibc/work/core2-64-oe-linux/tensorboard/1.12.2-r0/bazel/output_base/external/org_tensorflow, there is nothing but only a zip naming 6ef428bd6e83b0930266bf922eaa2f4a60e8328a.tar.gz.

I will try compile again.

**Comment by d-wang03** [comment]
OK, build success!
Many thanks!

**Comment by d-wang03** [comment]
An additional information: 
If enable "uninative" in distro conf file, the bazel will not work correctly.
comment the following two lines will resolve it:
#require conf/distro/include/yocto-uninative.inc
#INHERIT += "uninative"

**Comment by hongxu-jia** [comment]
> enable "uninative" in distro conf file, the bazel will not work correctly.

Yes, I explicitly disable it
https://github.com/hongxu-jia/meta-tensorflow/commit/1631906049bca322ec27fdf082ec0b89424f8a4e
