### ISSUE TITLE
"Bazel Input/ouput error" while building tensorflow

### ISSUE THREAD

**Issue by erikhh** [hongxu-jia/meta-tensorflow#3]
I'm trying to incorporate Tensorflow in our Yocto build.
Because of other layers we use I'm tied to the thud release for the time being. Since meta-tensorflow is based on the master branch of meta-openembedded I'm cherry picking all your patches to meta-openembedded to the thud branch on a fork of the meta-openembedded repo in an attempt to get it going on the thud release of yocto. You can see here: https://github.com/erikhh/meta-openembedded/commits/thud

It's now at least complete enough to have all the missing recipes present and it does start building. But at the point where it's done with building Bazel itself and about to start with Tensorflow-native I get this error:

```
| DEBUG: Executing shell function do_configure
| ./bazel: line 4: /home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git/bazel.real: Input/output error
| ./bazel: line 4: /home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git/bazel.real: Success
| Traceback (most recent call last):
|   File "./configure.py", line 1701, in <module>
|     main()
|   File "./configure.py", line 1557, in main
|     check_bazel_version('0.19.0', '0.21.0')
|   File "./configure.py", line 457, in check_bazel_version
|     ['./bazel', '--batch', '--bazelrc=/dev/null', 'version'])
|   File "./configure.py", line 147, in run_shell
|     output = subprocess.check_output(cmd)
|   File "/home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/recipe-sysroot-native/usr/lib/python3.5/subprocess.py", line 316, in check_output
|     **kwargs).stdout
|   File "/home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/recipe-sysroot-native/usr/lib/python3.5/subprocess.py", line 398, in run
|     output=stdout, stderr=stderr)
| subprocess.CalledProcessError: Command '['./bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 126
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/temp/log.do_configure.11726)
```

It seems to me that the bazel-native it has build is not quite functional. But I don't really know where to look further to try and get it going. Can you maybe give me a pointer in the right direction to look in?

**Comment by hongxu-jia** [comment]
I am afraid it caused by the following commit
https://github.com/hongxu-jia/meta-tensorflow/commit/25af4daadaafeb67f167791303e9fe8fb9f34903

Please try `bitbake tensorflow-native -ccleansstate && bitbake tensorflow-native',
but it will have the similar error for other recipes.

Or start a new build from scratch

**Comment by erikhh** [comment]
Hello Hongxu,

Thank you for taking the time to look into this issue.

My problems seems to be a different one that the one pointed out in 25af4da.
For me, the compilation of tensorflow-native just fails with this error all the time, not just when it's being used from different recipes.
But I managed to make progress! I happened to notice on the Tensorflow repository that their own cross compilation scripts use a ```ubuntu:14.04``` (Trusty) Docker image to run.
My own Yocto build environment was running on the latest LTS release, Ubuntu 18.04 (Bionic). 

So I have downgraded my build host to Ubuntu 14.04, just to see if anything would change. 
And now tensorflow-native does compile sucessfully to completion. 

I think the problem is that the produced Bazel simply does not work on Ubuntu 18.04 for some reason. Not sure if the root cause of that problem is with the Yocto build process, Bazel or Tensorflow. I only know that on the [Bazel website](https://docs.bazel.build/versions/master/install-ubuntu.html) Ubuntu 18.04 is listed as a supported Ubuntu version.

**Comment by hongxu-jia** [comment]
Hi erikhh,
I am afraid no relation with Ubuntu 18.04, I pull a ubuntu 18.04 docker image for build
and build tensorflow-native with your thud branch (https://github.com/erikhh/meta-openembedded)
And the oe-core and meta-java is also switch to thud branch.

It build successfully and no failure.
Please start a new build from scratch and try again

**Comment by erikhh** [comment]
Hi Hongxu,

I'm giving up on this approach. I can't get any different result on 18.04 then Bazel giving "Input/output error" every time. I started completely clean so many times but it just ends like this.

I'm going to try to just build Tensorflow for the Raspberry Pi like this: https://www.tensorflow.org/install/source_rpi separately and I'll just make a simple recipe to put all the resulting binaries in the correct places.

Thanks for your help. I'll give it another go when the rest of my layers are also ready to move to Warrior.

**Comment by hongxu-jia** [comment]
I am afraid the build of Tensorflow for the Raspberry Pi
is not complete as normal build.

How about tarball /home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/ and let me have a look what has happened.

**Comment by hongxu-jia** [comment]
Execute the following command in your build:
$ cd /home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git
$ export JAVA_HOME="/home/vagrant/build/poky/academy/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/recipe-sysroot-native/usr/lib/jvm/openjdk-8-native"
$ ./bazel --batch --bazelrc=/dev/null version
Is it the same failure as you have before?
$ ../recipe-sysroot-native/usr/bin/bazel  --batch --bazelrc=/dev/null version
Is it still fail?
$ ls -al ./bazel.real ../recipe-sysroot-native/usr/bin/bazel
Are they duplicated?

**Comment by erikhh** [comment]
This is very kind of you, thank you so much.

You can find the tarbal of my tensorflow-native directory [here](https://1drv.ms/u/s!AleaQTODjZgE4TZdkSqfLyauMcfZ).

And this is the output I get from the commands you asked for:
```
./bazel --batch --bazelrc=/dev/null version
./bazel: line 4: /home/vagrant/build/poky/tensorflow/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git/bazel.real: Input/output error
./bazel: line 4: /home/vagrant/build/poky/tensorflow/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git/bazel.real: Success
```
and 
```
../recipe-sysroot-native/usr/bin/bazel --batch --bazelrc=/dev/null version
file is invalid or corrupted (missing end of central directory record)
Cannot find central directory
FATAL: Failed to open Bazel as a zip file: (error: 5): Input/output error
```
The two files seem to be slightly different in size:
```
ls -al ./bazel.real ../recipe-sysroot-native/usr/bin/bazel
-rwxr-xr-x 1 vagrant vagrant 116623674 Apr 19 13:23 ./bazel.real
-rwxr-xr-x 5 vagrant vagrant 116625544 Apr 19 13:23 ../recipe-sysroot-native/usr/bin/bazel
```
And for good measure, this is the reported build configuration.
```
Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "raspberrypi-cm3"
DISTRO               = "poky"
DISTRO_VERSION       = "2.6.2"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU           = "hard"
meta
meta-poky
meta-yocto-bsp       = "HEAD:50f33d3bfebcbfb1538d932fb487cfd789872026"
meta-mender-core     = "HEAD:efffaa74fdc6fe4d2d102fb6f626b2c189e088e4"
meta-raspberrypi     = "HEAD:c71d79efc5a06a0c896c278c94f5b14413bb4d69"
meta-mender-raspberrypi = "HEAD:efffaa74fdc6fe4d2d102fb6f626b2c189e088e4"
meta-oe
meta-multimedia
meta-networking
meta-python          = "HEAD:9f338438af70330e3d83a23af88ef5eddb152d12"
meta-java            = "HEAD:b0c74493af1415dfd3b6caf77ebc677ed4e0fdaa"
meta-rtlwifi         = "HEAD:fd7ca0ca47c7095ced62a5a7cdef040dff87fb76"
meta-tessa           = "HEAD:81ad47fbb5ba96a3e3d893fd470601e680ad9007"
```

**Comment by hongxu-jia** [comment]
I am afraid it is issue of `bazel' which is generated by bazel-native.

$ cd /home/vagrant/build/poky/tensorflow/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/
$ ls -al output/bazel sysroot-destdir/home/vagrant/build/poky/tensorflow/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/bin/bazel
$ export JAVA_HOME="/home/vagrant/build/poky/tensorflow/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/lib/jvm/openjdk-8-native"
$ output/bazel --batch --bazelrc=/dev/null version

The following output is expected:
...
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: dcbfc227-8f6e-4f32-82bb-9048bb4eb313
Build label: 0.21.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Apr 11 07:53:55 2019 (1554969235)
Build timestamp: 1554969235
Build timestamp as int: 1554969235
...

If call `output/bazel' still failed with
...
file is invalid or corrupted (missing end of central directory record)
Cannot find central directory
FATAL: Failed to open Bazel as a zip file: (error: 5): Input/output error
...

Please rebuild bazel-native and try above steps again.
`bitbake bazel-native -ccleansstate && bitbake bazel-native'

If still failure, I guess there is a defect to buid bazel-native
on your host which bazel is a java program. It depends on openjdk-8-native,
zip-native and coreutils-native. Without a reproducible build,
it's hard to debug it.

**Comment by erikhh** [comment]
I'll get you a reproducible setup. Just need a few days.

**Comment by erikhh** [comment]
I have setup a the Vagrant environment here: https://github.com/erikhh/tensor-pi-build that is similar to my own build setup. For me this reproduces the issue 100% of the time, just follow the instructions in the readme.

**Comment by hongxu-jia** [comment]
As https://github.com/erikhh/tensor-pi-build/blob/master/Vagrantfile:
I guess the issue is: your cpu number of vm is 4 which causing
multiple bazel build failed, each bazel build use 4 cpu by default,
please tweak classes/bazel.bbclass to set 1, such as:

diff --git a/classes/bazel.bbclass b/classes/bazel.bbclass
index 5d3a00a..2305b98 100644
--- a/classes/bazel.bbclass
+++ b/classes/bazel.bbclass
@@ -68,7 +68,7 @@ bazel_do_configure () {
     cat > "${S}/bazelrc" <<-EOF
 build --verbose_failures
 build --spawn_strategy=standalone --genrule_strategy=standalone
-build --jobs=${@oe.utils.cpu_count()}
+build --jobs=1
 test --verbose_failures --verbose_test_summary
 test --spawn_strategy=standalone --genrule_strategy=standalone

Or add more cpu to your vm

**Comment by hongxu-jia** [comment]
Thanks your reproduce steps, I could debug on it.
In poky, it enable "uninative" which causing the bazel will not work correctly.

The reason why I could not find it previously is my build using oe-core rather
than which does not enable  "uninative"

Please pull the following fix
https://github.com/hongxu-jia/meta-tensorflow/commit/1631906049bca322ec27fdf082ec0b89424f8a4e

**Comment by hongxu-jia** [comment]
While enabling uninative, it uses `patchelf --set-interpreter' to change the dynamic loader
("ELF interpreter") of executables, which causing java binary `bazel' not working.

On my build, I could not reproduce the issue, because I use `zip -A bazel' to correct it.
but I don't know why the correction did not work on your build.

So directly disable uninative by unset UNINATIVE_LOADER

**Comment by erikhh** [comment]
I ran a fresh build from scratch today. It was updated to include your fix for this (f965e20c).
But it still fails with the same error.
Afterwards I checked `~/build/poky/tessa/tmp/work/x86_64-linux/tensorflow-native/1.13.0-r0/git/bazelrc`

It looked like this:
```
build --verbose_failures
build --spawn_strategy=standalone --genrule_strategy=standalone
build --jobs=1
test --verbose_failures --verbose_test_summary
test --spawn_strategy=standalone --genrule_strategy=standalone

build --linkopt=-Wl,-latomic
build --linkopt=-Wl,--no-as-needed
build --host_linkopt=-Wl,--no-as-needed

build --strip=never

fetch --distdir=/home/vagrant/build/poky/tessa/downloads
build --distdir=/home/vagrant/build/poky/tessa/downloads
```

So the fix did what it's supposed to do. But it does not resolve the issue. 

I don't have a machine at my disposal with more than 4 CPU cores.

**Comment by hongxu-jia** [comment]
See my following comments, do your build contains https://github.com/hongxu-jia/meta-tensorflow/commit/1631906049bca322ec27fdf082ec0b89424f8a4e?

**Comment by erikhh** [comment]
Yes, it does, I simply pulled in the latest from the repo before starting a fresh build. So it has both commits included.

Could it maybe still be failing because the command that fails ( `./bazel --batch --bazelrc=/dev/null 'version'` ) does not include any bazelrc file?

**Comment by hongxu-jia** [comment]
That's weird, I am pretty sure I could reproduce the issue and the fix could resolve it.

Let's double check
$cd /home/vagrant/build/poky/tessa/tmp/work/x86_64-linux/bazel-native/0.21.0-r0

# Check both of bazle is the same
$ ls -al output/bazel image/home/vagrant/build/poky/tessa/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/bin/bazel 
-rwxr-xr-x 7 vagrant vagrant 116623948 Apr 24 16:10 image/home/vagrant/build/poky/tessa/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/bin/bazel
-rwxr-xr-x 1 vagrant vagrant 116623948 Apr 24 14:38 output/bazel

$ export JAVA_HOME="/home/vagrant/build/poky/tessa/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/tensorflow/1.13.0-r0/recipe-sysroot-native/usr/lib/jvm/openjdk-8-native"

$ output/bazel --batch --bazelrc=/dev/null 'version'
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: e5ccb662-803f-4295-bcd2-ec4f854f871f
Build label: 0.21.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 24 14:30:06 2019 (1556116206)
Build timestamp: 1556116206
Build timestamp as int: 1556116206

$ image/home/vagrant/build/poky/tessa/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/bin/bazel --batch --bazelrc=/dev/null 'version'
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 00c4edd1-caf0-4898-b244-fc0d2aa1b1bb
Build label: 0.21.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 24 14:30:06 2019 (1556116206)
Build timestamp: 1556116206
Build timestamp as int: 1556116206

**Comment by hongxu-jia** [comment]
> Could it maybe still be failing because the command that fails ( `./bazel --batch --bazelrc=/dev/null 'version'` ) does not include any bazelrc file?
It has already include bazelrc, ./bazel is a wrapper which add $BAZEL_ARGS to bazel.real which set
bazelrc

**Comment by hongxu-jia** [comment]
If still call `output/bazel --batch --bazelrc=/dev/null version' ok but
call `image/home/vagrant/build/poky/tessa/tmp/work/x86_64-linux/bazel-native/0.21.0-r0/recipe-sysroot-native/usr/bin/bazel --batch --bazelrc=/dev/null version' failed,

it means my disable uninative not work, would you please add the following
to your local.conf
...
INHERIT_remove = "uninative"
...

Or: 
--- a/meta-poky/conf/distro/poky.conf
+++ b/meta-poky/conf/distro/poky.conf
@@ -96,4 +96,3 @@ require conf/distro/include/poky-world-exclude.inc
 require conf/distro/include/no-static-libs.inc
 require conf/distro/include/yocto-uninative.inc
 require conf/distro/include/security_flags.inc
-INHERIT += "uninative"

**Comment by erikhh** [comment]
Yes! That does make all the difference in the world. It's going through now. Thank you so much for all your help!

Now I just encountered one additional error in the tensorboard recipe. It was complaining it couldn't find `rev`.

I fixed that with:
```
--- a/recipes-framework/tensorflow/tensorboard_1.12.2.bb
+++ b/recipes-framework/tensorflow/tensorboard_1.12.2.bb
@@ -3,6 +3,8 @@ your TensorFlow runs and graphs."
 LICENSE = "Apache-2.0"
 LIC_FILES_CHKSUM = "file://LICENSE;md5=e74df23890b9521cc481e3348863e45d"

+DEPENDS = "util-linux-native"
+
 SRC_URI = "git://github.com/tensorflow/tensorboard.git; \
            file://0001-customize-for-Yocto.patch \
            file://BUILD \
```
I saw `tensorboard` is using `cut` and `rev` in the `do_configure_append ()` function.
Is this correct way to fix this? I'm still very much a newbie when it comes to Openembedded/Yocto.

**Comment by hongxu-jia** [comment]
No, you could not use `=' to assign, you should use `+=' to append

But tensorborad already implicitly depends on util-linux-native:
$ bitbake tensorboard -g
you will get recipe depends map from recipe-depends.dot
"tensorboard" -> "python3-native"
"python3-native" -> "util-linux-native"

**Comment by hongxu-jia** [comment]
> No, we usually do not use '=' to override DEPENDS, but use '+=' to append
> 
> But tensorborad already implicitly depends on util-linux-native:
> $ bitbake tensorboard -g
> you will get recipe depends map from recipe-depends.dot
> "tensorboard" -> "python3-native"
> "python3-native" -> "util-linux-native"

Oh, my test is on master branch rather than thud
there is no '"python3-native" -> "util-linux-native"' on thud branch.

But there is still util-linux-native on tensorboard,
whatever add  DEPENDS += "util-linux-native" could fix command 'rev' missing.

**Comment by hongxu-jia** [comment]
If you allocate only 4 cpu to your vb, it will takes a very long time to build tensorflow

**Comment by erikhh** [comment]
Yes it takes very long, roughly 6 hours. But it works eventually. So, that solves my issue. Thanks again!
