### ISSUE TITLE
Tensorboard dependency issues & fix

### ISSUE THREAD

**Issue by aakbar5** [hongxu-jia/meta-tensorflow#7]
https://github.com/hongxu-jia/meta-tensorflow/blob/master/recipes-framework/tensorflow/tensorboard_1.12.2.bb needs to have dependency of `util-linux-native` as recipe is using `rev` utility which is only available in `util-linux-native`. I would recommend to have dependency on bazel and protobuf as well to avoid further issues.

`DEPENDS = "bazel-native protobuf-native util-linux-native protobuf"`

**Comment by hongxu-jia** [comment]
Agree

**Comment by hongxu-jia** [comment]
https://github.com/hongxu-jia/meta-tensorflow/commit/2507dd595cf60e1b33f1503aa84d2cc5645c9bdc
